# 1. List the number of films per category.
USE sakila;

SELECT COUNT(DISTINCT film_id) AS number_of_films, category_id
FROM film_category
GROUP BY category_id;

# 2. Retrieve the store ID, city, and country for each store.
# store_id, city and country
SELECT store_id, city, country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id);

# STORE ID
SELECT store_id, address_id
FROM store;

# ADDRESS (NOT NEEDED)
SELECT address_id, city_id
FROM address;

# CITY
SELECT city_id, city, country_id
FROM city;

# COUNTRY
SELECT country_id, country
FROM country;


# NESTING: SHOW NAME OF CITY AND NAME OF COUNTRY
SELECT city, country
FROM city
INNER JOIN country
ON city.country_id = country.country_id;

# 3. Calculate the total revenue generated by each store in dollars.
SELECT amount, customer_id
FROM payment;

SELECT store_id
FROM store;

SELECT store_id, customer_id
FROM customer;

SELECT customer_id, SUM(amount) AS total_amount
FROM payment
GROUP BY customer_id;